#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Bash
rm -rf "$HOME/.bash_profile"
rm -rf "$HOME/.bashrc"
rm -rf "$HOME/.bash_aliases"
ln -sf "$DOTFILES/bash/.bash_profile" "$HOME/.bash_profile"
ln -sf "$DOTFILES/bash/.bashrc" "$HOME/.bashrc"
ln -sf "$DOTFILES/bash/.bash_aliases" "$HOME/.bash_aliases"

if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

# Kitty
rm -rf "$HOME/.config/kitty"
ln -s "$DOTFILES/kitty" "$HOME/.config/kitty"

# i3wm
rm -rf "$HOME/.config/i3"
ln -s "$DOTFILES/i3" "$HOME/.config"
