#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Bash
rm -rf "$HOME/.bash_profile"
rm -rf "$HOME/.bashrc"
rm -rf "$HOME/.bash_aliases"
ln -sf "$DOTFILES/bash/.bash_profile" "$HOME/.bash_profile"
ln -sf "$DOTFILES/bash/.bashrc" "$HOME/.bashrc"
ln -sf "$DOTFILES/bash/.bash_aliases" "$HOME/.bash_aliases"

if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

# Kitty
rm -rf "$HOME/.config/kitty"
ln -s "$DOTFILES/kitty" "$HOME/.config/kitty"

# Tmux
rm -rf "$HOME/.tmux.conf"
rm -rf "$HOME/.tmux"
ln -sf "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$DOTFILES/tmux" "$HOME/.tmux"

if ! command -v git &> /dev/null
then
  echo >&2 "Git is not installed, cannot install tmux plugin manager. Skipping..."
else
  rm -rf "$HOME/.tmux/plugins/tpm"
  git clone "https://github.com/tmux-plugins/tpm" "$HOME/.tmux/plugins/tpm"
  tmux source "$HOME/.tmux.conf"
  chmod a+x "$HOME/.tmux/plugins/tpm/scripts/install_plugins.sh"
  . "$HOME/.tmux/plugins/tpm/scripts/install_plugins.sh"
fi

# i3wm
rm -rf "$HOME/.config/i3"
ln -s "$DOTFILES/i3" "$HOME/.config"
