vim.lsp.enable("clangd")
vim.lsp.enable("lua_ls")
vim.lsp.enable("yamlls")
vim.lsp.enable("biome")
vim.lsp.enable("rust-analyzet")
vim.lsp.enable("rust-analyzer")

vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, {})
vim.keymap.set("n", "<leader>gr", vim.lsp.buf.references, {})
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, {})
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, {})
vim.keymap.set("n", "<leader>gf", vim.lsp.buf.format, {})
vim.keymap.set("n", "<leader>?", vim.diagnostic.open_float, {})
