alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias v='nvim'
alias vb='nvim ~/.bashrc'
alias vim='nvim'
alias cdp='cd ~/projects'
alias ll='ls -laF'
alias la='ls -A'
alias l='ls -CF'
alias grep='rg'
alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
